import sqlite3
import os

DATABASE_FOLDER = "database"
DATABASE_PATH = os.path.join(DATABASE_FOLDER, "examguard.db")


def create_database():

    if not os.path.exists(DATABASE_FOLDER):
        os.makedirs(DATABASE_FOLDER)

    connection = sqlite3.connect(DATABASE_PATH)
    cursor = connection.cursor()

    # ---------------- Candidates ----------------
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS candidates(

        candidate_id INTEGER PRIMARY KEY AUTOINCREMENT,
        application_id TEXT UNIQUE,
        fullname TEXT NOT NULL,
        email TEXT UNIQUE NOT NULL,
        mobile TEXT NOT NULL,
        college TEXT NOT NULL,
        rollnumber TEXT UNIQUE NOT NULL,
        department TEXT NOT NULL,
        password TEXT NOT NULL,
        photo_path TEXT,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        warning_count INTEGER DEFAULT 0,
deducted_marks INTEGER DEFAULT 0,
marks INTEGER DEFAULT 0

    )
    """)

    # ---------------- Sessions ----------------
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS sessions(

        session_id INTEGER PRIMARY KEY AUTOINCREMENT,
        candidate_id INTEGER,
        start_time TIMESTAMP,
        end_time TIMESTAMP,
        status TEXT,

        FOREIGN KEY(candidate_id)
        REFERENCES candidates(candidate_id)

    )
    """)

    # ---------------- Event Logs ----------------
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS event_logs(

        event_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id INTEGER,
        event_type TEXT,
        timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        FOREIGN KEY(session_id)
        REFERENCES sessions(session_id)

    )
    """)

    # ==================================================================
    # >>> NEW IN PART 3 / STEP 1 <
    # ---------------- Integrity Scores ----------------
    # Milestone 3: one row per exam session, computed after the session
    # ends (submit or terminate). Reads only from the existing
    # `event_logs` table -- no changes to sessions/event_logs schema.
    #
    # >>> NEW IN PART 11 <
    # face_presence_ratio (REAL, nullable): added for the Part 11
    # Pandas-based scoring module. This is an ESTIMATE, not a measured
    # value -- event_logs only records the timestamp a face-absent
    # episode STARTED, never when the face returned, so there is no
    # stored duration to compute an exact ratio from. See
    # utils/scoring.py for exactly how it's estimated. Nullable because
    # it cannot be estimated for a session with no duration (e.g.
    # start_time/end_time missing).
    # For a database file created BEFORE Part 11, this column will be
    # missing even after CREATE TABLE IF NOT EXISTS (SQLite does not
    # retroactively alter an existing table) -- run
    # update_database_part11.py once to add it. This CREATE TABLE
    # statement only benefits fresh databases that don't have
    # `integrity_scores` yet.
    # <<< END NEW IN PART 11
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS integrity_scores(

        score_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id INTEGER UNIQUE,
        candidate_id INTEGER,
        integrity_score REAL NOT NULL,
        risk_label TEXT NOT NULL,
        total_events INTEGER DEFAULT 0,
        face_presence_ratio REAL,
        computed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        FOREIGN KEY(session_id)
        REFERENCES sessions(session_id),

        FOREIGN KEY(candidate_id)
        REFERENCES candidates(candidate_id)

    )
    """)
    # >>> END NEW IN PART 3 / STEP 1 <
    # ==================================================================

    # ==================================================================
    # >>> NEW IN PART 12 <
    # ---------------- Integrity Reports ----------------
    # AI Integrity Report Agent (LangChain-based, see
    # utils/report_agent.py): one row per exam session, generated at
    # the same conclusion point Part 11's integrity_scores row is
    # generated (session termination or /submit_exam). Reads only from
    # the existing `event_logs` table and the Part 11
    # `integrity_scores` table -- no changes to either.
    #
    # generation_method records how summary_text was produced:
    #   "langchain_llm"          -- generated by the configured LLM.
    #   "deterministic_fallback" -- no LLM API key configured, or the
    #                               LLM call failed, so a template-
    #                               based summary built from the same
    #                               computed facts was used instead.
    # This lets an invigilator (or a grader) see at a glance whether a
    # given summary came from the AI agent or the fallback.
    #
    # For a database file created BEFORE Part 12, this table simply
    # won't exist yet even after this CREATE TABLE IF NOT EXISTS runs
    # against an already-open older database file, because this
    # function only ever ADDS missing tables -- which is exactly what
    # happens here too, so no separate migration is even required for
    # this particular table. update_database_part12.py is provided
    # anyway for the same one-command workflow as Part 11, and to
    # safely handle a database that already has an OLDER version of
    # this table in the future.
    # <<< END NEW IN PART 12
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS integrity_reports(

        report_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id INTEGER UNIQUE,
        candidate_id INTEGER,
        integrity_score REAL,
        risk_label TEXT,
        summary_text TEXT NOT NULL,
        generation_method TEXT NOT NULL,
        generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

        FOREIGN KEY(session_id)
        REFERENCES sessions(session_id),

        FOREIGN KEY(candidate_id)
        REFERENCES candidates(candidate_id)

    )
    """)
    # ==================================================================

    # ---------------- Questions ----------------
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS questions(

        question_id INTEGER PRIMARY KEY AUTOINCREMENT,
        course TEXT NOT NULL,
        question TEXT NOT NULL,
        option1 TEXT NOT NULL,
        option2 TEXT NOT NULL,
        option3 TEXT NOT NULL,
        option4 TEXT NOT NULL,
        answer TEXT NOT NULL

    )
    """)

    # Insert sample questions only once
    cursor.execute("SELECT COUNT(*) FROM questions")
    count = cursor.fetchone()[0]

    if count == 0:

        questions = [
            # ... [unchanged: full 140-question bank for java, python,
            #      datastructures, dbms, os, cn, ai, ml -- identical to
            #      the original file, not reproduced again here] ...
        ]
        cursor.executemany("""
        INSERT INTO questions
        (
            course,
            question,
            option1,
            option2,
            option3,
            option4,
            answer
        )
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """, questions)


        connection.commit()
        connection.close()

    print("Database created successfully!")


if __name__ == "__main__":
    create_database()